#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.2.4 effective-5.10 (swiftlang-6.2.4.1.4 clang-1700.6.4.2)
#ifndef PENGUIN_SWIFT_H
#define PENGUIN_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreData;
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="Penguin",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

typedef SWIFT_ENUM(NSInteger, BLEPowerStatus, open) {
  BLEPowerStatusBlePowerOff = 0,
  BLEPowerStatusBlePowerOn = 1,
};

@class NSEntityDescription;
@class NSManagedObjectContext;
SWIFT_CLASS_NAMED("CategoryTable")
@interface CategoryTable : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class NSString;
@interface CategoryTable (SWIFT_EXTENSION(Penguin))
@property (nonatomic, copy) NSString * _Nullable categoryIconUrl;
@property (nonatomic, copy) NSString * _Nullable color;
@property (nonatomic, copy) NSString * _Nullable framedIconUrl;
@property (nonatomic) int16_t id;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic) int16_t poiCount;
@property (nonatomic, copy) NSString * _Nullable categoryDesc;
@end

SWIFT_CLASS_NAMED("Edges_Table")
@interface Edges_Table : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@interface Edges_Table (SWIFT_EXTENSION(Penguin))
@property (nonatomic) int16_t id;
@property (nonatomic) int16_t floorID;
@property (nonatomic) int16_t x1;
@property (nonatomic) int16_t y1;
@property (nonatomic) int16_t p1FloorID;
@property (nonatomic) int16_t x2;
@property (nonatomic) int16_t y2;
@property (nonatomic) int16_t p2floorID;
@property (nonatomic) int16_t venueID;
@property (nonatomic) int16_t p1VenueID;
@property (nonatomic) int16_t p2VenueID;
@property (nonatomic) double connectedtheta;
@property (nonatomic) int16_t connecteddirection;
@property (nonatomic) int16_t campusID;
@property (nonatomic) BOOL outdoor;
@property (nonatomic, copy) NSString * _Nonnull p1Type;
@property (nonatomic) double longitude1;
@property (nonatomic) double longitude2;
@property (nonatomic) double latitude1;
@property (nonatomic) double latitude2;
@property (nonatomic, copy) NSString * _Nonnull p2Type;
@property (nonatomic, copy) NSString * _Nonnull type;
@property (nonatomic, copy) NSString * _Nonnull transitionType;
@end

typedef SWIFT_ENUM(NSInteger, ErrorCode, open) {
  ErrorCodeNoError = 0,
  ErrorCodeOSNotSupported = 1,
  ErrorCodeSignalLost = 2,
  ErrorCodeVenuesDetailsImportError = 3,
  ErrorCodeFloorsDetailsImportError = 4,
  ErrorCodeSettingsImportError = 5,
  ErrorCodeMapNorthAngleCalculationError = 6,
  ErrorCodeEdgesDetailsImportError = 7,
  ErrorCodeWiFiPermissionOFF = 8,
  ErrorCodeBLEPermissionOFF = 9,
  ErrorCodeDeviceRFNotAvailable = 10,
  ErrorCodeVenueRFNotAvailable = 11,
  ErrorCodeBluetoothNotEnabled = 12,
  ErrorCodeSensorInitialError = 13,
  ErrorCodeLocationServicesNotEnabled = 14,
  ErrorCodeErrorWithLoadingData = 15,
  ErrorCodeClientKeyIDNotSet = 17,
  ErrorCodeNoInternet = 18,
  ErrorCodeNonAuthorized = 19,
  ErrorCodeInvalidKey = 20,
  ErrorCodeLoadingNavigationError = 21,
  ErrorCodePathEmpty = 22,
  ErrorCodeSelectedPOI = 23,
  ErrorCodeLoadingErrorPathFailed = 24,
  ErrorCodeErrorInRemoteConfig = 25,
  ErrorCodeOfflinePEError = 26,
};

SWIFT_CLASS_NAMED("FloorSettings_Table")
@interface FloorSettings_Table : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@interface FloorSettings_Table (SWIFT_EXTENSION(Penguin))
@property (nonatomic, copy) NSString * _Nullable floorID;
@property (nonatomic, copy) NSString * _Nullable descriptions;
@property (nonatomic, copy) NSString * _Nullable value;
@end

typedef SWIFT_ENUM(NSInteger, FloorTransitionType, open) {
  FloorTransitionTypeNone = 0,
  FloorTransitionTypeEscalatorUp = 1,
  FloorTransitionTypeEscalatorDown = 2,
  FloorTransitionTypeElevatorUp = 3,
  FloorTransitionTypeElevatorDown = 4,
  FloorTransitionTypeUp = 5,
  FloorTransitionTypeDown = 6,
};

SWIFT_CLASS_NAMED("Floors_Table")
@interface Floors_Table : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class NSData;
@interface Floors_Table (SWIFT_EXTENSION(Penguin))
@property (nonatomic) int16_t id;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable descriptions;
@property (nonatomic, copy) NSData * _Nullable image;
@property (nonatomic) double scale_factor;
@property (nonatomic) int16_t level;
@property (nonatomic) int16_t icon_id;
@property (nonatomic, copy) NSString * _Nullable map_url;
@property (nonatomic) int16_t venue_id;
@property (nonatomic) int16_t map_north;
@property (nonatomic) int16_t threshold;
@property (nonatomic) int16_t far_dist;
@property (nonatomic) int16_t near_dest;
@property (nonatomic) int16_t serverConnectivityThreshold;
@property (nonatomic, copy) NSString * _Nullable alignmentCenter;
@property (nonatomic, copy) NSString * _Nullable alignmentOrigin;
@property (nonatomic) double alignmentScale;
@property (nonatomic) double alignmentScaleX;
@property (nonatomic) double alignmentScaleY;
@property (nonatomic) double alignmentRotation;
@property (nonatomic) double instructionDistanceThreshold;
@property (nonatomic) BOOL isDefault;
@property (nonatomic) BOOL isUnderground;
@property (nonatomic, copy) NSArray<NSNumber *> * _Nonnull xyToLongParameters;
@property (nonatomic, copy) NSArray<NSNumber *> * _Nonnull xyToLatParameters;
@property (nonatomic, copy) NSArray<NSNumber *> * _Nonnull longlatToXParameters;
@property (nonatomic, copy) NSArray<NSNumber *> * _Nonnull longlatToYParameters;
@property (nonatomic, copy) NSString * _Nullable geoJSONURL;
@property (nonatomic) int16_t mapWidth;
@property (nonatomic) int16_t mapHeight;
@property (nonatomic, copy) NSString * _Nullable label;
@property (nonatomic) int16_t updateStatus;
@property (nonatomic) BOOL isUncover;
@end

SWIFT_CLASS_NAMED("Gate_node")
@interface Gate_node : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@interface Gate_node (SWIFT_EXTENSION(Penguin))
@property (nonatomic) int16_t campus_id;
@property (nonatomic) int16_t edge_id;
@property (nonatomic) BOOL outdoor;
@property (nonatomic) int16_t update_status;
@property (nonatomic) int16_t id;
@property (nonatomic) int16_t venue_id;
@property (nonatomic) int16_t floor_id;
@property (nonatomic, copy) NSString * _Nonnull type;
@property (nonatomic) int16_t x;
@property (nonatomic) int16_t y;
@property (nonatomic) double longitude;
@property (nonatomic) double latitude;
@property (nonatomic) BOOL is_floor_gate_node;
@property (nonatomic) BOOL is_connected_gate_node;
@property (nonatomic) BOOL isCampusGate;
@end

SWIFT_CLASS_NAMED("Geofence_Table")
@interface Geofence_Table : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class NSDate;
@interface Geofence_Table (SWIFT_EXTENSION(Penguin))
@property (nonatomic) int16_t id;
@property (nonatomic) double longitude;
@property (nonatomic) double latitude;
@property (nonatomic) int16_t radius;
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSString * _Nullable geofenceDescription;
@property (nonatomic, copy) NSString * _Nullable endDate;
@property (nonatomic, copy) NSDate * _Nullable validity;
@end

SWIFT_CLASS_NAMED("Last_update_Table")
@interface Last_update_Table : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@interface Last_update_Table (SWIFT_EXTENSION(Penguin))
@property (nonatomic, copy) NSString * _Nullable tableName;
@property (nonatomic, copy) NSString * _Nullable lastUpdateTime;
@end

SWIFT_CLASS_NAMED("Localize")
@interface Localize : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@interface Localize (SWIFT_EXTENSION(Penguin))
@property (nonatomic, copy) NSString * _Nullable languageCode;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic) int16_t id;
@property (nonatomic, copy) NSString * _Nullable key;
@property (nonatomic, copy) NSString * _Nullable value;
@end

SWIFT_CLASS("_TtC7Penguin12PIAPIManager")
@interface PIAPIManager : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7Penguin17PILocationManager")
@interface PILocationManager : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7Penguin16PenguinUtilities")
@interface PenguinUtilities : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7Penguin16PoIPolygonsTable")
@interface PoIPolygonsTable : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@interface PoIPolygonsTable (SWIFT_EXTENSION(Penguin))
@property (nonatomic) int16_t id;
@property (nonatomic) int16_t floorid;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSData * _Nullable zoonpoint;
@property (nonatomic, copy) NSData * _Nullable zoon_center_point;
@property (nonatomic, copy) NSString * _Nullable categorycolor;
@property (nonatomic, copy) NSString * _Nullable iconUrl;
@property (nonatomic, copy) NSString * _Nullable framedIconUrl;
@property (nonatomic) BOOL landmark;
@property (nonatomic, copy) NSString * _Nullable landmarkIconUrl;
@property (nonatomic) int16_t venueId;
@property (nonatomic) int16_t categoryId;
@property (nonatomic) int16_t extrusionHeight;
@property (nonatomic, copy) NSString * _Nullable modelUri;
@property (nonatomic) double modelLatitude;
@property (nonatomic) double modelLongitude;
@property (nonatomic) BOOL showOnMap;
@property (nonatomic, copy) NSString * _Nullable landmarkFilledIconUrl;
@property (nonatomic, copy) NSData * _Nullable schedule;
@end

typedef SWIFT_ENUM(NSInteger, PositionScanningMode, open) {
  PositionScanningModeBackground = 1,
  PositionScanningModeFreeStyle = 2,
  PositionScanningModeNavigation = 3,
};

typedef SWIFT_ENUM(NSInteger, SDKOperation, open) {
  SDKOperationInitialize = 0,
  SDKOperationVenueDetection = 1,
  SDKOperationDataLoading = 2,
  SDKOperationReadyForPositionUpdate = 3,
  SDKOperationGetPosition = 4,
  SDKOperationNewVenueDataLoading = 5,
};

typedef SWIFT_ENUM(NSInteger, ServerConnectivityStatus, open) {
  ServerConnectivityStatusDisconnected = 1,
  ServerConnectivityStatusPoor = 2,
  ServerConnectivityStatusMedium = 3,
  ServerConnectivityStatusExcellent = 4,
  ServerConnectivityStatusEmptyBLEScans = 5,
};

typedef SWIFT_ENUM(NSInteger, SourceConnectionStatus, open) {
  SourceConnectionStatusBleConnected = 0,
  SourceConnectionStatusGpsConnected = 1,
  SourceConnectionStatusBleDisconnected = 2,
  SourceConnectionStatusInitializing = 3,
  SourceConnectionStatusGpsNotResponding = 4,
};

typedef SWIFT_ENUM(NSInteger, SourceGPSConnectionStatus, open) {
  SourceGPSConnectionStatusGpsConnected = 0,
  SourceGPSConnectionStatusGpsNotResponding = 1,
};

SWIFT_CLASS_NAMED("SystemSetting")
@interface SystemSetting : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@interface SystemSetting (SWIFT_EXTENSION(Penguin))
@property (nonatomic, copy) NSString * _Nullable desc;
@property (nonatomic, copy) NSString * _Nullable value;
@end

SWIFT_CLASS_NAMED("UUID_Table")
@interface UUID_Table : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@interface UUID_Table (SWIFT_EXTENSION(Penguin))
@property (nonatomic) int16_t id;
@property (nonatomic, copy) NSString * _Nullable uuid_data;
@property (nonatomic) int16_t update_status;
@end

SWIFT_CLASS("_TtC7Penguin7UtilGps")
@interface UtilGps : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("VenueSettingsTable")
@interface VenueSettingsTable : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@interface VenueSettingsTable (SWIFT_EXTENSION(Penguin))
@property (nonatomic, copy) NSString * _Nullable venueID;
@property (nonatomic, copy) NSString * _Nullable descriptions;
@property (nonatomic, copy) NSString * _Nullable value;
@end

SWIFT_CLASS_NAMED("VenueTable")
@interface VenueTable : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@interface VenueTable (SWIFT_EXTENSION(Penguin))
@property (nonatomic) int16_t id;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable arabic_name;
@property (nonatomic) int16_t is_wifi;
@property (nonatomic) int16_t is_ble;
@property (nonatomic) int16_t is_mix;
@property (nonatomic) int16_t campusId;
@property (nonatomic, copy) NSString * _Nullable points;
@property (nonatomic, copy) NSString * _Nullable centerPoint;
@property (nonatomic) BOOL is_default;
@property (nonatomic) BOOL isUnderground;
@property (nonatomic) int16_t extrusionHeight;
@property (nonatomic, copy) NSString * _Nullable threeDUri;
@property (nonatomic) double threeDCenterLat;
@property (nonatomic) double threeDCenterLng;
@property (nonatomic, copy) NSArray<NSNumber *> * _Nonnull connectedVenues;
@end

typedef SWIFT_ENUM(NSInteger, WarningCode, open) {
  WarningCodeNoWarning = 0,
  WarningCodeAccelerometerSensorNotAvailable = 1,
  WarningCodeMagnetometerSensorNotAvailable = 2,
  WarningCodeMagnetometerAccuracyLow = 3,
  WarningCodeGyroSensorNotAvailable = 4,
  WarningCodeOrientationSensorNotAvailable = 5,
  WarningCodeBarometerSensorNotAvailable = 6,
};

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
